---
- name: Start hcloud_instance
  hosts: localhost
  gather_facts: no
  tasks:
    - hetzner.hcloud.server:
        name: benito-greybeard
        state: absent

    - name: Delete DNS records
      community.general.cloudflare_dns:
        account_email: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_ACCOUNT_EMAIL') }}"
        account_api_key: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_ACOOUNT_TOKEN') }}"
        zone: openshift.pub
        record: "{{ item }}"
        state: absent
        type: A
        comment: Benito Greybeard's VM
      with_items:
        - 'bg'
        - '*.apps.bg'

